[tool.pytest.ini_options]
addopts = "--strict-markers"
markers = []

log_cli = true
log_cli_level = "WARNING"

log_file = "logs/my.log"
log_file_level = "WARNING"

# ======================================================================
# Other log options
# ======================================================================
# log_auto_indent (string)
# log_cli (bool):                Enable log display during test run
# log_cli_date_format (string)
# log_cli_format (string)
# log_cli_level (string)
# log_date_format (string)
# log_file_date_format (string)
# log_file_format (string)
# log_file_level (string)
# log_file_mode (string)
# log_file (string):             Default value for --log-file
# log_format (string):           Default value for --log-format
# log_level (string):            Default value for --log-level

[tool.ruff]
line-length = 120

[tool.ruff.lint]
ignore = [
    "D203",  # one-blank-line-before-class
    "D213",  # multi-line-summary-second-line
    "COM812",
    "ISC001",
]
select = ["F", "E", "W", "I001"] # pyflakes, pycodestyle, isort

[tool.ruff.lint.isort]
case-sensitive = true
